[package]
name = "sift4g-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive"] }
